### PR TITLE
DalamudPackager update. no updates needed for API11

### PR DESCRIPTION
**Pull request by Gasteno**
updated dalamudpackager to 11. Code didn't need updates.

### CODE REVIEW

**Comment by zeroeightysix** [comment]
Thanks, I can test this tomorrow. Does this need a new version release?

**Comment by Gasteno** [comment]
> Thanks, I can test this tomorrow. Does this need a new version release?

I am not entirely sure how the release process through Dalamud works. I would think a new version release is needed since the Dalamud team updated the API requirement from 10 to 11 after the 7.1 update. I am also not sure if you can just resubmit the current version since there are probably no updates needed.

**Comment by zeroeightysix** [comment]
I'll quickly ask in the discord then :)

EDIT: It will need a bump. Hopefully we should be back tomorrow.

**Comment by zeroeightysix** [comment]
Thanks!

**Comment by Gasteno** [comment]
> Thanks!

Anytime!. Thanks for what you do!!!

**Pull request merged**
